// Builds the setup page the player serves in setup mode: index.html with portal.css and portal.js inlined, lightly
// minified, gzipped, and written as a byte array to player/src/portal_page.h. No dependencies.
//
//   node player/portal/build.mjs        (from cartridge-player/)
//
// tests/portal.test.mjs imports buildPage() and checks the committed header holds exactly what it returns.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { gzipSync } from "node:zlib";

const here = new URL("./", import.meta.url);
const headerUrl = new URL("../src/portal_page.h", import.meta.url);

/** The page's budget on the device: flash is plentiful, but the page is sent on every open of the captive sheet. */
export const MAX_GZIP_BYTES = 12 * 1024;

const read = (name) => readFileSync(new URL(name, here), "utf8");

/** Drops comments and collapses whitespace outside quoted strings, so values like data URIs stay intact. */
function minifyCss(css) {
  return css
    .split(/("(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*'|\/\*[\s\S]*?\*\/)/)
    .map((part, index) => {
      if (index % 2 === 1) return part.startsWith("/*") ? "" : part;
      return part
        .replace(/\s+/g, " ")
        .replace(/\s*([{};,>])\s*/g, "$1")
        .replace(/:\s+/g, ":")
        .replace(/;}/g, "}");
    })
    .join("")
    .trim();
}

/**
 * Drops whole-line comments, indentation and blank lines, and nothing else: line breaks stay, so automatic semicolon
 * insertion, strings and regular expressions mean exactly what they did. portal.js only uses whole-line comments.
 */
function minifyJs(js) {
  return js
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line !== "" && !line.startsWith("//"))
    .join("\n");
}

function minifyHtml(html) {
  return html
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/>\s*\n\s*</g, "><")
    .replace(/\s*\n\s*/g, " ")
    .trim();
}

/** The page as the player serves it, before compression. */
export function buildPage() {
  const html = minifyHtml(read("index.html"));
  const link = '<link rel="stylesheet" href="portal.css">';
  const script = '<script src="portal.js"></script>';
  if (!html.includes(link) || !html.includes(script)) throw new Error("index.html must link portal.css and portal.js");
  return html
    .replace(link, () => `<style>${minifyCss(read("portal.css"))}</style>`)
    .replace(script, () => `<script>${minifyJs(read("portal.js"))}</script>`);
}

/** gzip at level 9, with the header's OS byte fixed so every machine writes the same bytes for the same zlib. */
export function gzipPage(page) {
  const gz = gzipSync(Buffer.from(page, "utf8"), { level: 9 });
  gz[9] = 255;
  return gz;
}

function header(gz) {
  const rows = [];
  for (let i = 0; i < gz.length; i += 16) {
    rows.push(`  ${Array.from(gz.subarray(i, i + 16), (byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`);
  }
  return `// Generated by player/portal/build.mjs from player/portal/index.html, portal.css and portal.js: don't edit.
// Change those files, then run \`node player/portal/build.mjs\` from cartridge-player/ to regenerate it.
// The setup page, gzipped: serve it with Content-Encoding: gzip.
#pragma once
#include <stddef.h>
#include <stdint.h>
#ifdef ARDUINO
#include <pgmspace.h>
#else
#ifndef PROGMEM
#define PROGMEM
#endif
#endif

static const uint8_t PORTAL_PAGE_GZ[] PROGMEM = {
${rows.join("\n")}
};
static const size_t PORTAL_PAGE_GZ_LEN = ${gz.length};
`;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const gz = gzipPage(buildPage());
  if (gz.length > MAX_GZIP_BYTES) throw new Error(`The page is ${gz.length} bytes gzipped, over ${MAX_GZIP_BYTES}`);
  writeFileSync(headerUrl, header(gz));
  console.log(`Wrote ${fileURLToPath(headerUrl)}: ${gz.length} bytes gzipped`);
}
